# Generated by Django 3.1.2 on 2020-10-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A Note', max_length=50, verbose_name='name')),
                ('intro', models.CharField(max_length=250, verbose_name='intro')),
                ('description', models.TextField(verbose_name='full')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
