# Generated by Django 3.1.2 on 2020-10-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
